name: ILibrary
version: 3.13.3
main: de.ancash.ILibrary
api-version: 1.13
author: Ancash

commands:
#   fedit:
#      usage: "ยง7/fedit <file>"
   nbtn:
      usage:
      - "ยง7/nbtn edit (edit item in hand in gui)"
      - "ยง7/nbtn s/ser/serialize (serialize item in hand to json & yaml)"
      - "ยง7/nbtn tsdc (measures ser/de time)"